services:
  iris:
    image: containers.intersystems.com/intersystems/iris-community:latest-preview
    ports:
      - 6172:1972
      - 6173:52773
    environment:
      - IRISUSERNAME=test
      - IRISPASSWORD=test
      - IRISNAMESPACE=TEST
    working_dir: /home/irisowner/langchain-iris
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./:/home/irisowner/langchain-iris
